### ISSUE TITLE
Syntax error in compressors.py: unterminated triple quote

### ISSUE THREAD

**Issue by jabowery** [bazingagin/npc_gzip#19] opened 2023-07-24 00:48 UTC
```
    def get_bits_per_char(self, original_fn: str) -> float:
        """
        Returns the compressed size of the original function
        in bits.

"""Test Compressors"""
```

**Comment by EliahKagan** [comment] 2023-07-24 01:16
This bug appears to have been introduced in https://github.com/bazingagin/npc_gzip/commit/404253f2256e898eb3e65815b5e9c4c611190331. The problem is not limited to closing `"""` quotes being missing. The implementation of `get_bits_per_char` has also gone away, as shown by this fragment of the diff:

```diff
-        """
-        with open(original_fn) as fo:
-            data = fo.read()
-            compressed_str = self.compressor.compress(data.encode("utf-8"))
-            return len(compressed_str) * 8 / len(data)
```

I've proposed a fix in #21 (for this issue and another one of apparently similar origin, #20).

**Closed as completed** 2023-07-24 03:29 UTC
